-- Seed therapist_profiles for 10 existing therapists (assumes auth.users and public.profiles already populated)

DELETE FROM public.therapist_profiles
WHERE user_id IN (
  '174fdf7b-8f2a-4aa2-85ac-e70f331621c2',
  'f2a42a89-87b9-460c-a29e-c09eca681021',
  '8454e604-876c-472e-942c-80c2271573a7',
  'ddee5c19-200d-4391-9e2a-b004ad78a68a',
  'eb9784dd-afed-4b2b-86de-9c08e0b23126',
  '93dcd7aa-cb19-46bf-82a7-6511507c2201',
  'fc730f96-6839-498e-ae55-b3a61ddd4b67',
  'd0c85e61-3a5f-48fd-b75d-dfec36ae628b',
  '41428325-84ee-4d14-a6c9-070474a90de6',
  '5c244bfe-1947-4c16-9ba6-f706f5fb73a0'
);

INSERT INTO public.therapist_profiles (
  id,
  user_id,
  application_id,
  name,
  tagline,
  bio,
  avatar_url,
  video_url,
  quote,
  license_number,
  specialties,
  specialities,
  modalities,
  languages,
  experience_years,
  years_experience,
  communication_style,
  session_format,
  session_focus,
  identity_tags,
  personality_tags,
  gender_identity,
  age_group,
  cultural_background,
  session_rates,
  availability,
  location_city,
  location_state,
  location_country,
  timezone,
  accepts_new_clients,
  online_sessions,
  in_person_sessions,
  verified,
  verification_date,
  is_active,
  setup_completed,
  setup_steps,
  pride_attributes,
  cancellation_policy,
  rescheduling_policy,
  lateness_policy,
  communication_policy,
  created_at,
  updated_at
)
VALUES
  (
    gen_random_uuid(),
    '174fdf7b-8f2a-4aa2-85ac-e70f331621c2',
    NULL,
    'Dr. Amelia Hart',
    'Integrative Psychotherapist',
    $$Dr. Amelia Hart is an integrative psychotherapist based in London with eight years of clinical experience supporting adults navigating major life transitions, workplace pressure, and recovery from traumatic experiences. Her training spans person centred counselling, trauma stabilisation protocols, and mindfulness based interventions, and she weaves them together to create steadiness for clients who feel overwhelmed by constant change. Amelia previously led wellbeing programmes in a national arts organisation, so she understands the pace, expectations, and relational demands placed on creative professionals and community leaders.

In sessions, Amelia balances clear psychoeducation with compassionate listening. She helps people trace the patterns between nervous system spikes, protective habits, and survival stories, while also translating those insights into tiny experiments they can try between meetings. Clients say her use of grounding exercises, breathwork, and visual mapping makes complex emotions feel tangible and workable. Amelia works with couples as well as individuals, particularly when relationships are strained by burnout, unresolved trauma, or fertility journeys.

Outside the therapy room, Amelia mentors early career therapists through a UK mentoring network and co-facilitates monthly reflective practice circles. She keeps her work current through ongoing training in trauma informed leadership and somatic resourcing, and she is committed to accessible care for LGBTQIA+ and neurodivergent clients. Her blend of warmth, structure, and practical planning helps people move from surviving to participating fully in the parts of life that matter most.$$,
    'https://images.unsplash.com/photo-1544723795-3fb6469f5b39?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=I2L5PsbG4wA',
    'Steady support for deep healing.',
    'BACP83241',
    ARRAY['Anxiety','Depression','Motivation and self-esteem','Trauma and abuse','PTSD'],
    ARRAY['Anxiety','Depression','Motivation and self-esteem','Trauma and abuse','PTSD'],
    ARRAY['Integrative/eclectic approach','Person-centered Therapy','Mindfulness-based Therapy (MBCT)'],
    ARRAY['English'],
    8,
    '5-10 years',
    'Supportive & Relational (I focus on creating safety, trust, and emotional validation)',
    'Calm & Process-Focused (My sessions emphasise pacing, safety, and careful exploration of feelings)',
    ARRAY['Adults','Couples','Professionals in transition'],
    ARRAY['Trauma-informed and gentle','Culturally sensitive and aware'],
    ARRAY['Supportive & Relational (I focus on creating safety, trust, and emotional validation)','Calm & Process-Focused (My sessions emphasise pacing, safety, and careful exploration of feelings)'],
    'female',
    '35-44',
    ARRAY['British'],
    '{"45min":85,"60min":115,"90min":170}'::jsonb,
    '{"monday":["09:00","14:00"],"tuesday":["10:30","16:30"],"wednesday":["09:00","12:30"],"thursday":["13:00","18:00"],"friday":["09:30","15:00"]}'::jsonb,
    'London',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    true,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY[]::text[],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  ),
  (
    gen_random_uuid(),
    'f2a42a89-87b9-460c-a29e-c09eca681021',
    NULL,
    'Priya Desai',
    'Counselling Psychologist',
    $$Priya Desai is a counselling psychologist who partners with adults and couples balancing diasporic identities, caregiving responsibilities, and ambitious careers. Across nine years in community mental health services and university wellbeing teams, she has specialised in integrating attachment work with mindfulness and family systems thinking. Priya draws on her lived experience as a second-generation British Indian woman and mother, creating space for clients to explore cultural narratives without losing sight of their personal voice.

During therapy, Priya actively adjusts the pace and style to match what her clients need in the moment. She combines somatic tracking, compassion-focused imagery, and structured experiments that help people try new relational boundaries, communication scripts, or mindfulness practices between sessions. Many clients arrive wanting to reduce anxiety rooted in intergenerational expectations, and Priya guides them to build self-trust while honouring their family stories. Couples appreciate how she helps them translate unspoken worries into collaborative problem-solving.

Beyond clinical practice, Priya co-hosts workshops on navigating dual heritage parenting and serves on the board of a South Asian mental health collective. She remains current through postgraduate certificates in trauma-sensitive yoga and perinatal mental health, and she routinely consults with other therapists to keep bias in check. Clients describe her as both grounded and energising, a combination that allows difficult conversations to feel safe while momentum toward change stays alive.$$,
    'https://images.unsplash.com/photo-1587614382346-ac5ce068fe85?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=U9Y1hZp1Z7Y',
    'Therapy that honours every part of you.',
    'HCPC76102',
    ARRAY['Anxiety','Family conflict','Relationship and intimacy issues','Race and racial identity','Trauma and abuse'],
    ARRAY['Anxiety','Family conflict','Relationship and intimacy issues','Race and racial identity','Trauma and abuse'],
    ARRAY['Integrative/eclectic approach','Mindfulness-based Therapy (MBCT)','Family systems therapy'],
    ARRAY['English','Hindi','Gujarati'],
    9,
    '5-10 years',
    'Flexible & Adaptive (I am constantly shifting tone/style depending on the client''s needs in the moment)',
    'Interactive & Dynamic (I switch it up with various techniques and exercises to keep energy high)',
    ARRAY['Adults','Couples','Second-generation families'],
    ARRAY['Culturally sensitive and aware','Trauma-informed and gentle'],
    ARRAY['Flexible & Adaptive (I am constantly shifting tone/style depending on the client''s needs in the moment)','Interactive & Dynamic (I switch it up with various techniques and exercises to keep energy high)'],
    'female',
    '35-44',
    ARRAY['South Asian'],
    '{"45min":80,"60min":110,"90min":160}'::jsonb,
    '{"monday":["11:00","17:00"],"tuesday":["09:00","12:00"],"wednesday":["11:30","18:30"],"thursday":["08:30","13:30"],"saturday":["10:00","12:00"]}'::jsonb,
    'Manchester',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    false,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY[]::text[],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  ),
  (
    gen_random_uuid(),
    '8454e604-876c-472e-942c-80c2271573a7',
    NULL,
    'Kwesi Mensah',
    'Chartered Psychotherapist',
    $$Kwesi Mensah is a chartered psychotherapist with eighteen years of experience working alongside men and women recovering from traumatic events, workplace discrimination, and leadership fatigue. Trained initially in cognitive behavioural therapy and organisational coaching, he later added compassion-focused and trauma-processing modalities to better address the layered impacts of racism and complex grief on performance. Kwesi has served as clinical lead for several community justice projects, offering therapy to frontline staff, returning citizens, and their families throughout London and Birmingham.

In session, Kwesi works with clear goals while keeping a deep respect for the pace each client needs. He collaborates on practical action plans, grounding exercises, and resilience rituals that connect everyday behaviours with long-term healing. He is known for translating policy language into human terms, helping clients who carry professional responsibility understand how to stay accountable without burning out. Many clients seek him specifically for support around anger, bereavement, and post-traumatic stress rooted in violent incidents or institutional betrayal.

Kwesi remains active in continuing professional development, training younger clinicians in anti-oppressive practice and supervising trauma teams across the UK. He volunteers with a church-based restorative justice initiative and facilitates monthly men’s wellbeing circles for Black community leaders. His steady, goal-oriented style gives clients both structure and hope, demonstrating that disciplined change and compassionate self-regard can exist side by side.$$,
    'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=JkLZ8vGeOaw',
    'Resilience grows when we practise together.',
    'UKCP55871',
    ARRAY['Anger management','Career difficulties','Grief and loss','PTSD','Trauma and abuse'],
    ARRAY['Anger management','Career difficulties','Grief and loss','PTSD','Trauma and abuse'],
    ARRAY['Cognitive Behavioural Therapy (CBT)','Trauma-focused therapy','Compassion Focused Therapy (CFT)'],
    ARRAY['English','French'],
    18,
    '10+ years',
    'Pragmatic & Problem-solving (I focus on offering clear, solution-oriented feedback with actionable takeaways)',
    'Structured & Goal-oriented (Sessions follow a clear agenda with measurable progress markers)',
    ARRAY['Adults','Executives','Community leaders'],
    ARRAY['Trauma-informed and gentle','Culturally sensitive and aware'],
    ARRAY['Pragmatic & Problem-solving (I focus on offering clear, solution-oriented feedback with actionable takeaways)','Structured & Goal-oriented (Sessions follow a clear agenda with measurable progress markers)'],
    'male',
    '45-54',
    ARRAY['Black African'],
    '{"45min":95,"60min":130,"90min":185}'::jsonb,
    '{"monday":["08:00","12:00"],"tuesday":["14:00","19:00"],"wednesday":["09:00","11:00"],"thursday":["15:00","19:00"],"friday":["08:30","12:30"]}'::jsonb,
    'Birmingham',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    true,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY[]::text[],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  ),
  (
    gen_random_uuid(),
    'ddee5c19-200d-4391-9e2a-b004ad78a68a',
    NULL,
    'Jade Thompson',
    'Cognitive Behavioural Therapist',
    $$Jade Thompson is a cognitive behavioural therapist based in Manchester who supports LGBTQ+ young adults, creatives, and emerging leaders managing anxiety, perfectionism, and identity stress. With four years of post-qualification experience, she blends CBT with interpersonal therapy, mindfulness, and creative exercises that help clients reconnect with their values. Jade previously worked in youth arts organisations and understands what it feels like to carry visibility while handling pressure to perform and represent an entire community.

Sessions with Jade are lively, interactive, and anchored in encouragement. She offers structured experiments, brief journaling prompts, and compassionate challenges that help clients take brave but manageable risks in their relationships, workplaces, and activism. Clients describe her as a thoughtful cheerleader who celebrates progress while staying honest about avoidance patterns. Jade particularly enjoys working on relationship repair, mood swings, and confidence building after episodes of public harassment or family conflict.

Outside the consulting room, Jade delivers workshops on queer joy and anxiety regulation, co-facilitates community support groups, and volunteers with a local trans and non-binary youth charity. She continues her professional development through training in trauma-informed mindfulness and inclusive sex education, ensuring her practice stays affirming and contemporary. Her approach gives clients a grounded space to rewrite their stories and cultivate resilience without sacrificing authenticity.$$,
    'https://images.unsplash.com/photo-1525186402429-b4ff38bedbec?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=6oTurM7gESE',
    'Your story deserves joyful space.',
    'BACP94763',
    ARRAY['Anxiety','Depression','LGBT-related issues','Motivation and self-esteem','Relationship and intimacy issues'],
    ARRAY['Anxiety','Depression','LGBT-related issues','Motivation and self-esteem','Relationship and intimacy issues'],
    ARRAY['Mindfulness-based Therapy (MBCT)','Person-centered Therapy','Interpersonal Therapy'],
    ARRAY['English','Spanish'],
    4,
    '2-5 years',
    'Motivational & Encouraging (I focus on boosting morale, using encouragement and gentle challenge)',
    'Interactive & Dynamic (I switch it up with various techniques and exercises to keep energy high)',
    ARRAY['Young adults','LGBTQ+ clients','Creatives'],
    ARRAY['LGBTQ+ friendly and affirming','Trauma-informed and gentle'],
    ARRAY['Motivational & Encouraging (I focus on boosting morale, using encouragement and gentle challenge)','Interactive & Dynamic (I switch it up with various techniques and exercises to keep energy high)'],
    'female',
    '25-34',
    ARRAY['Black Caribbean'],
    '{"45min":70,"60min":95,"90min":140}'::jsonb,
    '{"tuesday":["11:00","19:00"],"wednesday":["10:00","14:00"],"thursday":["12:00","18:00"],"friday":["09:00","12:00"],"saturday":["11:00","13:00"]}'::jsonb,
    'Manchester',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    true,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY['LGBTQ+ community advocate'],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  ),
  (
    gen_random_uuid(),
    'eb9784dd-afed-4b2b-86de-9c08e0b23126',
    NULL,
    'James O''Connor',
    'Career and Wellbeing Coach',
    $$James O'Connor is a career and wellbeing coach who integrates psychotherapy principles with executive coaching to help professionals navigate burnout, imposter feelings, and leadership transitions. Over six years he has supported clients across finance, tech start-ups, and the public sector, drawing on CBT, interpersonal therapy, and trauma-focused approaches to make workplace challenges easier to shift. Before qualifying as a therapist, James led talent development programmes and understands the pressures of delivering results while caring for a team.

James collaborates with clients to set practical goals, map mindsets that block progress, and build rituals that support focus and energy. He provides clear feedback alongside self-compassion practices so clients can experiment with new behaviours without shame. Many of his sessions include personalised planning tools, ethical decision-making frameworks, and guided reflections on values. He is particularly skilled in helping neurodivergent professionals advocate for accommodations and design sustainable routines.

Beyond one-to-one sessions, James delivers workshops on psychological safety, consults with organisations around inclusive leadership, and mentors early-career coaches. He remains active in professional supervision and advanced training in trauma-informed coaching to ensure his work stays rigorous. Clients appreciate his grounded honesty and structured optimism, which helps them feel both supported and accountable while they design careers that align with their wellbeing.$$,
    'https://images.unsplash.com/photo-1544723795-4325377613c6?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=0g9poWKKpbU',
    'Clarity for your next courageous step.',
    'BACP61584',
    ARRAY['Anxiety','Career difficulties','Executive and Professional coaching','Motivation and self-esteem'],
    ARRAY['Anxiety','Career difficulties','Executive and Professional coaching','Motivation and self-esteem'],
    ARRAY['Cognitive Behavioural Therapy (CBT)','Interpersonal Therapy','Trauma-focused therapy'],
    ARRAY['English'],
    6,
    '5-10 years',
    'Pragmatic & Problem-solving (I focus on offering clear, solution-oriented feedback with actionable takeaways)',
    'Structured & Goal-oriented (Sessions follow a clear agenda with measurable progress markers)',
    ARRAY['Adults','Professionals','Career changers'],
    ARRAY['Culturally sensitive and aware','Neurodiversity affirming'],
    ARRAY['Pragmatic & Problem-solving (I focus on offering clear, solution-oriented feedback with actionable takeaways)','Structured & Goal-oriented (Sessions follow a clear agenda with measurable progress markers)'],
    'male',
    '35-44',
    ARRAY['British'],
    '{"45min":75,"60min":105,"90min":155}'::jsonb,
    '{"monday":["07:30","11:30"],"tuesday":["15:00","19:00"],"wednesday":["08:30","12:30"],"thursday":["16:00","19:00"],"friday":["09:30","12:30"]}'::jsonb,
    'London',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    false,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY[]::text[],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  ),
  (
    gen_random_uuid(),
    '93dcd7aa-cb19-46bf-82a7-6511507c2201',
    NULL,
    'Sofia Bennett',
    'Family Systems Therapist',
    $$Sofia Bennett is a family systems therapist working with blended families, adolescents, and parents who are navigating complex identities. For three years she has supported mixed-heritage households in Leeds, combining mindfulness, compassion-focused practices, and structural family therapy to reduce conflict and strengthen connection. Her background in youth work and community mediation informs her ability to translate between generations and reframe differences as sources of resilience. Sofia also collaborates with dietitians and school specialists when disordered eating or learning needs are part of the picture.

In sessions, Sofia creates a collaborative map of family dynamics and encourages everyone to name what safety looks like. She uses reflective listening, embodied grounding, and creative storytelling exercises to help families externalise blame and move toward curiosity. Parents appreciate how she blends research on attachment, neurodiversity, and cultural humility into practical home routines. Adolescents appreciate her calm humour and clear boundaries, which make it easier to stay engaged even when conversations feel vulnerable.

Sofia invests in ongoing learning through courses on trauma-informed parenting, eating disorder prevention, and antiracist practice in schools. She partners with local charities to host bilingual parenting circles and provides consultation to youth services designing inclusive programming. Clients describe her presence as steady, gentle, and inclusive, offering both structure and warmth as families experiment with new ways of being together.$$,
    'https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=GZC3yNjh0X8',
    'Gentle insight for sustainable change.',
    'UKCP66320',
    ARRAY['Eating disorders','Depression','Family conflict','Parenting issues'],
    ARRAY['Eating disorders','Depression','Family conflict','Parenting issues'],
    ARRAY['Family systems therapy','Mindfulness-based Therapy (MBCT)','Compassion Focused Therapy (CFT)'],
    ARRAY['English','Spanish'],
    3,
    '2-5 years',
    'Supportive & Relational (I focus on creating safety, trust, and emotional validation)',
    'Exploratory & Insight-based (Sessions unfold organically, focusing on deep reflection and meaning-making)',
    ARRAY['Parents','Adolescents','Mixed heritage families'],
    ARRAY['Trauma-informed and gentle','Neurodiversity affirming'],
    ARRAY['Supportive & Relational (I focus on creating safety, trust, and emotional validation)','Exploratory & Insight-based (Sessions unfold organically, focusing on deep reflection and meaning-making)'],
    'female',
    '35-44',
    ARRAY['Mixed Heritage'],
    '{"45min":78,"60min":108,"90min":158}'::jsonb,
    '{"monday":["09:30","13:30"],"tuesday":["12:00","17:00"],"wednesday":["09:00","11:30"],"thursday":["14:00","18:00"],"friday":["10:00","13:00"]}'::jsonb,
    'Leeds',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    false,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY[]::text[],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  ),
  (
    gen_random_uuid(),
    'fc730f96-6839-498e-ae55-b3a61ddd4b67',
    NULL,
    'Laura Abiola',
    'Neurodiversity Specialist Counsellor',
    $$Laura Abiola is a neurodiversity specialist counsellor based in Birmingham with seven years of experience supporting adults and parents living with autism, ADHD, and chronic health conditions. Trained in integrative counselling and CBT, she focuses on translating evidence-based strategies into real-life systems that honour each client’s sensory profile and pacing needs. Laura has worked across NHS neurodevelopmental services and community disability organisations, giving her insight into how health, employment, and education pathways intersect.

Sessions with Laura balance practical planning with compassionate validation. She works collaboratively to build tailored regulation kits, sustainable routines, and communication plans that fit within each family’s energy budget. Laura uses visual tools, shared documents, and rhythm-based grounding practices to make therapy accessible for clients who process information differently. She is passionate about helping carers maintain their wellness while advocating for their loved ones.

Laura remains active in professional development through training in polyvagal theory, chronic pain management, and culturally responsive autism support. She co-facilitates peer groups for Black neurodivergent adults and provides consultation to organisations improving workplace accessibility. Clients describe her as gentle, thorough, and encouraging, offering a dependable space to untangle overwhelm and celebrate progress in realistic steps.$$,
    'https://images.unsplash.com/photo-1520962918287-7448c2878f65?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=8SOQduoLgRw',
    'You can thrive while living with complexity.',
    'HCPC88215',
    ARRAY['Autism','Chronic illness','Concentration, memory and focus (ADHD)','Parenting issues','Anxiety'],
    ARRAY['Autism','Chronic illness','Concentration, memory and focus (ADHD)','Parenting issues','Anxiety'],
    ARRAY['Integrative/eclectic approach','Cognitive Behavioural Therapy (CBT)','Person-centered Therapy'],
    ARRAY['English','French'],
    7,
    '5-10 years',
    'Flexible & Adaptive (I am constantly shifting tone/style depending on the client''s needs in the moment)',
    'Calm & Process-Focused (My sessions emphasise pacing, safety, and careful exploration of feelings)',
    ARRAY['Adults','Parents','Caregivers'],
    ARRAY['Neurodiversity affirming','Trauma-informed and gentle'],
    ARRAY['Flexible & Adaptive (I am constantly shifting tone/style depending on the client''s needs in the moment)','Calm & Process-Focused (My sessions emphasise pacing, safety, and careful exploration of feelings)'],
    'female',
    '45-54',
    ARRAY['British'],
    '{"45min":90,"60min":125,"90min":180}'::jsonb,
    '{"monday":["08:30","12:30"],"tuesday":["13:00","18:00"],"wednesday":["09:30","12:30"],"thursday":["15:00","19:00"],"friday":["08:30","10:30"]}'::jsonb,
    'Birmingham',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    true,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY[]::text[],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  ),
  (
    gen_random_uuid(),
    'd0c85e61-3a5f-48fd-b75d-dfec36ae628b',
    NULL,
    'Dr. Daniel Fraser',
    'Consultant Clinical Psychologist',
    $$Dr. Daniel Fraser is a consultant clinical psychologist with twenty-two years of practice working in NHS acute settings and private clinics across Edinburgh. He specialises in complex mood disorders, trauma recovery, and obsessive compulsive presentations, integrating CBT, psychodynamic therapy, and trauma-focused modalities to match each client’s history. Daniel’s background includes leading multidisciplinary teams in inpatient services, so he understands the interplay between medication, therapy, and lifestyle when rebuilding stability.

During therapy, Daniel co-designs highly structured plans that break long-term goals into manageable experiments. He combines data-driven tracking, compassionate inquiry, and skills training to help clients measure progress while staying attuned to the emotional work beneath each symptom. Clients seeking support for bipolar disorder, intrusive thoughts, or long-standing traumatic memories often remark on his ability to hold hope while staying practical about relapse prevention.

Daniel teaches on postgraduate programmes, supervises early-career psychologists, and contributes to research on compassionate risk management. He also consults with charities supporting survivors of childhood trauma, ensuring his practice remains connected to community voices. Clients experience him as steady, prepared, and quietly encouraging, a presence that makes intensive work feel both safe and purposeful.$$,
    'https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=hMcJLfju6_g',
    'We plan your recovery with steady intention.',
    'HCPC70294',
    ARRAY['Bipolar disorder','OCD','Depression','Trauma and abuse','Anger management'],
    ARRAY['Bipolar disorder','OCD','Depression','Trauma and abuse','Anger management'],
    ARRAY['Cognitive Behavioural Therapy (CBT)','Trauma-focused therapy','Psychodynamic therapy'],
    ARRAY['English','German'],
    22,
    '10+ years',
    'Pragmatic & Problem-solving (I focus on offering clear, solution-oriented feedback with actionable takeaways)',
    'Structured & Goal-oriented (Sessions follow a clear agenda with measurable progress markers)',
    ARRAY['Adults','Couples','Healthcare professionals'],
    ARRAY['Trauma-informed and gentle','Culturally sensitive and aware'],
    ARRAY['Pragmatic & Problem-solving (I focus on offering clear, solution-oriented feedback with actionable takeaways)','Structured & Goal-oriented (Sessions follow a clear agenda with measurable progress markers)'],
    'male',
    '55+',
    ARRAY['British'],
    '{"45min":100,"60min":140,"90min":195}'::jsonb,
    '{"monday":["10:00","14:00"],"tuesday":["09:00","11:00"],"wednesday":["13:00","18:00"],"thursday":["09:30","12:30"],"friday":["11:00","15:00"]}'::jsonb,
    'Edinburgh',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    true,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY[]::text[],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  ),
  (
    gen_random_uuid(),
    '41428325-84ee-4d14-a6c9-070474a90de6',
    NULL,
    'Aisha Khan',
    'Child and Adolescent Therapist',
    $$Aisha Khan is a child and adolescent therapist who helps young people rebuild confidence after bullying, anxiety spikes, and school avoidance. With eight years in school counselling and community youth services, she blends CBT, mindfulness-based strategies, and play-informed techniques to make therapy engaging and practical. Aisha draws on her South Asian heritage and fluency in Urdu and Punjabi to help families navigate cultural expectations while centring a child’s wellbeing.

In session, Aisha creates a predictable rhythm that gives teenagers and caregivers room to talk honestly about fear, shame, and hope. She uses exposure ladders, sensory regulation plans, and strengths-based storytelling so young people can take small risks with support. Families appreciate how she translates therapeutic ideas into simple action steps, such as communication scripts or morning routines that reduce conflict. Aisha is especially skilled at supporting young people who feel pressure to succeed academically while managing racialised experiences at school.

Outside therapy, Aisha collaborates with safeguarding leads, offers parent workshops on digital wellbeing, and volunteers with an anti-bullying helpline. She keeps her skills sharp through advanced trainings in trauma-informed education and culturally responsive CBT. Clients describe her as calm, reliable, and creative, capable of turning tricky topics into moments of courage and connection.$$,
    'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=iX6w3RgW0_E',
    'Safety, science, and soulful care.',
    'BACP57821',
    ARRAY['Anxiety','Bullying','Phobias','Race and racial identity','Trauma and abuse'],
    ARRAY['Anxiety','Bullying','Phobias','Race and racial identity','Trauma and abuse'],
    ARRAY['Cognitive Behavioural Therapy (CBT)','Mindfulness-based Therapy (MBCT)','Person-centered Therapy'],
    ARRAY['English','Urdu','Punjabi'],
    8,
    '5-10 years',
    'Motivational & Encouraging (I focus on boosting morale, using encouragement and gentle challenge)',
    'Interactive & Dynamic (I switch it up with various techniques and exercises to keep energy high)',
    ARRAY['Children','Adolescents','Families'],
    ARRAY['Culturally sensitive and aware','Trauma-informed and gentle'],
    ARRAY['Motivational & Encouraging (I focus on boosting morale, using encouragement and gentle challenge)','Interactive & Dynamic (I switch it up with various techniques and exercises to keep energy high)'],
    'female',
    '35-44',
    ARRAY['South Asian'],
    '{"45min":68,"60min":90,"90min":135}'::jsonb,
    '{"monday":["09:00","12:00"],"tuesday":["10:00","13:00"],"wednesday":["14:00","18:00"],"thursday":["09:00","11:00"],"saturday":["09:30","12:30"]}'::jsonb,
    'Liverpool',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    false,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY[]::text[],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  ),
  (
    gen_random_uuid(),
    '5c244bfe-1947-4c16-9ba6-f706f5fb73a0',
    NULL,
    'Rowan Farouk',
    'Creative Psychotherapist',
    $$Rowan Farouk is a creative psychotherapist working primarily with queer and trans adults exploring identity, neurodivergence, and the lingering impact of medical trauma. With two years of post-qualification experience, Rowan integrates integrative counselling, mindfulness, and compassion-focused practice to build collaborative, experimental spaces. They previously worked in community arts and refugee support, bringing a deep commitment to accessible, culturally responsive care.

Rowan’s sessions are exploratory and co-created. They invite clients to experiment with grounding techniques, guided imagery, and expressive writing that translate insights into lived change. Rowan holds space for the messy, hopeful parts of transition and recovery, helping clients name both grief and possibility. They are particularly passionate about supporting people who have felt unseen in traditional services, including queer and trans clients of colour and neurodivergent adults.

Beyond one-to-one work, Rowan co-facilitates peer-led groups on creative resilience, contributes to workshops on trans healthcare navigation, and collaborates with community organisers on inclusive policy advocacy. They stay current through mentorship with senior queer therapists and advanced training in trauma-informed mindfulness. Clients appreciate Rowan’s calm curiosity and willingness to learn alongside them, which makes therapy feel collaborative, validating, and brave.$$,
    'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=facearea&w=400&h=400&q=80',
    'https://www.youtube.com/watch?v=9wK5LjZfZPw',
    'We experiment, learn, and grow together.',
    'UKCP77405',
    ARRAY['Anxiety','Autism','Concentration, memory and focus (ADHD)','LGBT-related issues','Tourettes syndrome'],
    ARRAY['Anxiety','Autism','Concentration, memory and focus (ADHD)','LGBT-related issues','Tourettes syndrome'],
    ARRAY['Integrative/eclectic approach','Mindfulness-based Therapy (MBCT)','Compassion Focused Therapy (CFT)'],
    ARRAY['English','Arabic'],
    2,
    '0-2 years',
    'Supportive & Relational (I focus on creating safety, trust, and emotional validation)',
    'Exploratory & Insight-based (Sessions unfold organically, focusing on deep reflection and meaning-making)',
    ARRAY['Queer adults','Neurodivergent adults','Creative professionals'],
    ARRAY['LGBTQ+ friendly and affirming','Neurodiversity affirming'],
    ARRAY['Supportive & Relational (I focus on creating safety, trust, and emotional validation)','Exploratory & Insight-based (Sessions unfold organically, focusing on deep reflection and meaning-making)'],
    'non-binary',
    '25-34',
    ARRAY['Other'],
    '{"45min":65,"60min":88,"90min":130}'::jsonb,
    '{"monday":["12:00","18:00"],"tuesday":["09:00","11:30"],"wednesday":["13:00","17:00"],"thursday":["10:00","15:00"],"friday":["09:30","12:30"]}'::jsonb,
    'Glasgow',
    NULL,
    'UK',
    'Europe/London',
    true,
    true,
    false,
    true,
    '2025-09-01T09:00:00Z',
    true,
    true,
    '{"profile":true,"services":true,"policies":true,"billing":true}'::jsonb,
    ARRAY['Trans-led support facilitator'],
    '48 hours'' notice required for cancellations; sessions cancelled later incur the full fee.',
    'Reschedule at least 24 hours in advance to retain the full session credit.',
    'Sessions shorten after 15 minutes of lateness; the full fee applies after 20 minutes.',
    'Replies within 24 hours via secure messaging in the client portal.',
    '2025-09-25T09:00:00Z',
    '2025-09-25T09:00:00Z'
  );
