// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://curxanzghxehsjyoyukj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN1cnhhbnpnaHhlaHNqeW95dWtqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMTA3OTgsImV4cCI6MjA3Mzg4Njc5OH0.HMY6x_Bdnb2za71o0w0q1_gQZCdCXeS2Zav-gmLJY_U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});