// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jegunzgsuyylcvberwcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImplZ3VuemdzdXl5bGN2YmVyd2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQ1MjcsImV4cCI6MjA3Mzc5MDUyN30.RX2gljBrmCEi9ycC281Z6TaSPtVXaUJ7UBFgrThG8f0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});